name: CI/CD Pipeline 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore
        run: dotnet restore ./research-rig.sln

      # Run unit and integration tests
      - name: Test
        run: dotnet test ./research-rig.sln --configuration Release

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore
        run: dotnet restore ./research-rig.sln

      # Build the project
      - name: Build
        run: dotnet build ./research-rig.sln --configuration Release --no-restore

      # Publish the project
      - name: Publish
        run: dotnet publish ./research-rig.sln --configuration Release --no-build

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Build Docker images
      - name: Build Docker Images
        run: |
          docker build -t authentication-service -f Authentication.Service/Dockerfile.authentication Authentication.Service
          docker build -t transaction-service -f Transaction.service/Dockerfile.transaction Transaction.service
          docker build -t authorization-gateway -f Authorization.Gateway/Dockerfile.gateway Authorization.Gateway

      # Tag and Push Docker images to ECR
      - name: Tag and Push Docker Images to ECR
        run: |
          docker tag authentication-service:latest ${{ secrets.AWS_ECR_REGISTRY }}/authentication-service:latest
          docker tag transaction-service:latest ${{ secrets.AWS_ECR_REGISTRY }}/transaction-service:latest
          docker tag authorization-gateway:latest ${{ secrets.AWS_ECR_REGISTRY }}/authorization-gateway:latest

          docker push ${{ secrets.AWS_ECR_REGISTRY }}/authentication-service:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/transaction-service:latest
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/authorization-gateway:latest

      # Deploy to ECS
      - name: Deploy to ECS
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: ecs update-service --cluster rig-clusters --service rig-servies --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
